//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FakeSpider.rc
//
#define IDD_ABOUTBOX                    100
#define ID_SPECIAL_SERIES_PASS          101
#define IDR_MAINFRAME                   128
#define IDR_FakeSpiderTYPE              129
#define IDS_MESSAGE_BEGIN_NEW_GAME      129
#define IDB_ABOUT                       130
#define IDS_MESSAGE_RESTART_CURRENT_GAME 130
#define IDS_MESSAGE_PASS_NEW_SERIES_IMPOSIBBLE 131
#define IDS_MESSAGE_REPLACE_EXISTING_SAVE 132
#define IDS_MESSAGE_LOAD_SAVED_GAME     133
#define IDS_MESSAGE_GAME_SAVE_FAILED    134
#define IDD_HEAVITY_SWITCHER            135
#define IDD_DIFFICUTLY_SWITCHER         135
#define IDS_MESSAGE_GAME_LOAD_FAILED    135
#define IDB_CASTS                       136
#define IDS_MESSAGE_YOU_WIN             136
#define IDD_DIALOG1                     137
#define IDD_GAME_SETTINGS               137
#define IDS_MESSAGE_SAVE_GAME           137
#define IDB_CARD_CLUB_ACE               138
#define IDS_MESSAGE_RESET_STATISTICS    138
#define IDB_CARD_CLUB_2                 139
#define IDS_LABEL_SCORES                139
#define IDB_CARD_CLUB_3                 140
#define IDS_LABEL_TURNS                 140
#define IDB_CARD_CLUB_4                 141
#define IDS_STRING141                   141
#define IDS_MESSAGE_TITLE               141
#define IDB_CARD_CLUB_5                 142
#define IDB_CARD_CLUB_6                 143
#define IDB_CARD_CLUB_7                 144
#define IDB_CARD_CLUB_8                 145
#define IDB_CARD_CLUB_9                 146
#define IDB_CARD_CLUB_10                147
#define IDB_CARD_CLUB_JACK              148
#define IDB_CARD_CLUB_QUEEN             150
#define IDB_CARD_CLUB_KING              151
#define IDB_CARD_DIAMOND_ACE            152
#define IDB_CARD_DIAMOND_2              153
#define IDB_CARD_DIAMOND_3              154
#define IDB_CARD_DIAMOND_4              155
#define IDB_BITMAP1                     156
#define IDB_CARD_DIAMOND_5              156
#define IDB_CARD_DIAMOND_6              157
#define IDB_CARD_DIAMOND_7              158
#define IDB_CARD_DIAMOND_8              159
#define IDB_CARD_DIAMOND_9              160
#define IDB_CARD_DIAMOND_10             161
#define IDB_CARD_DIAMOND_JACK           162
#define IDB_CARD_DIAMOND_QUEEN          163
#define IDB_CARD_DIAMOND_KING           164
#define IDB_CARD_HEART_ACE              165
#define IDB_CARD_HEART_2                166
#define IDB_CARD_HEART_3                167
#define IDB_CARD_HEART_4                168
#define IDB_CARD_HEART_5                169
#define IDB_CARD_HEART_6                170
#define IDB_CARD_HEART_7                171
#define IDB_CARD_HEART_8                172
#define IDB_CARD_HEART_9                173
#define IDB_CARD_HEART_10               174
#define IDB_CARD_HEART_JACK             175
#define IDB_CARD_HEART_QUEEN            176
#define IDB_CARD_HEART_KING             177
#define IDB_CARD_SPADE_ACE              178
#define IDB_CARD_SPADE_2                179
#define IDB_CARD_SPADE_3                180
#define IDB_CARD_SPADE_4                181
#define IDB_CARD_SPADE_5                182
#define IDB_CARD_SPADE_6                183
#define IDB_CARD_SPADE_7                184
#define IDB_CARD_SPADE_8                185
#define IDB_CARD_SPADE_9                186
#define IDB_CARD_SPADE_10               187
#define IDB_CARD_SPADE_JACK             188
#define IDB_CARD_SPADE_QUEEN            189
#define IDB_CARD_SPADE_KING             190
#define IDB_CARDBACK                    191
#define IDB_GAG                         192
#define IDB_FELT                        193
#define IDD_STATISTICS                  194
#define IDD_DIALOG2                     195
#define IDD_STATISTICS_TAB              195
#define IDI_SPIDER                      196
#define IDSOUND_PASS_NEW_SERIES         197
#define IDSOUND_RELEASE_CARD            198
#define IDSOUND_SHOW_VALID_TURN         199
#define IDSOUND_NO_VALID_TURN           200
#define IDSOUND_TAKE_CARD               201
#define IDR_WAVE1                       202
#define IDSOUND_YOU_WIN                 202
#define IDR_WAVE2                       204
#define IDB_BITMAP2                     205
#define IDB_BACK                        205
#define IDC_LOH_EASY                    1000
#define IDC_DIFFICUTLY_EASY             1000
#define IDC_LOH_MEDIUM                  1001
#define IDC_OPTION_USEANIMATION         1001
#define IDC_DIFFICUTLY_MEDIUM           1001
#define IDC_LOH_HEAVY                   1002
#define IDC_OPTION_AUTOSAVING           1002
#define IDC_DIFFICUTLY_HEAVY            1002
#define IDB_RESET                       1002
#define IDC_OPTION_AUTOLOADING          1003
#define IDC_TAB                         1003
#define IDC_OPTION_CHECKONSAVING        1004
#define IDC_RECORD                      1004
#define IDC_OPTION_CHECKONLOADING       1005
#define IDC_WINS_PERCENT                1005
#define IDC_CHECK6                      1006
#define IDC_OPTION_USESOUND             1006
#define IDC_LOSSES_PERCENT              1006
#define IDC_SHAREOFWINS                 1007
#define IDC_SHAREOFWINS_PERCENT         1007
#define IDC_WINS_MAX                    1008
#define IDC_LOSSES_MAX                  1009
#define IDC_CURRENT_MAX                 1010
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_32779                        32779
#define ID_32780                        32780
#define ID_32781                        32781
#define ID_32782                        32782
#define IDMI_NEW_GAME                   32783
#define IDMI_RESTART_GAME               32784
#define IDMI_UNDO_TURN                  32785
#define IDMI_SHOW_VALID_TURN            32786
#define IDMI_DIFFICUTLY_LEVEL           32787
#define IDMI_STATICTICS                 32788
#define IDMI_GAME_SETTINGS              32789
#define IDMI_SAVE_GAME                  32790
#define IDMI_OPEN_SAVED_GAME            32791
#define IDMI_INVOKE_HELP                32792
#define IDMI_ABOUT                      32793
#define IDMI_TAKE_NEW_SERIES            32794
#define IDMI_TAKE_CARDS                 32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
